export const CURRENCY = "INR";

export const PAYMENT_MODE = {
  ONLINE: "ONLINE",
  COD: "COD",
};

export const ORDER_PAYMENT_STATUS = {
  CREATED: "CREATED",
  PENDING_CASH_COLLECTION: "PENDING_CASH_COLLECTION",
  PAID: "PAID",
  CASH_COLLECTED: "CASH_COLLECTED",
  PARTIALLY_REMITTED: "PARTIALLY_REMITTED",
  COD_RECONCILED: "COD_RECONCILED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

export const ORDER_SETTLEMENT_STATUS = {
  PENDING: "PENDING",
  PARTIAL: "PARTIAL",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
};

export const OWNER_TYPE = {
  ADMIN: "ADMIN",
  SELLER: "SELLER",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
  CUSTOMER: "CUSTOMER",
};

export const WALLET_STATUS = {
  ACTIVE: "ACTIVE",
  FROZEN: "FROZEN",
  CLOSED: "CLOSED",
};

export const LEDGER_DIRECTION = {
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",
};

export const LEDGER_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REVERSED: "REVERSED",
};

export const LEDGER_TRANSACTION_TYPE = {
  ORDER_ONLINE_PAYMENT_CAPTURED: "ORDER_ONLINE_PAYMENT_CAPTURED",
  ORDER_COD_COLLECTED: "ORDER_COD_COLLECTED",
  SELLER_PAYOUT_PENDING: "SELLER_PAYOUT_PENDING",
  SELLER_PAYOUT_PROCESSED: "SELLER_PAYOUT_PROCESSED",
  RIDER_PAYOUT_PENDING: "RIDER_PAYOUT_PENDING",
  RIDER_PAYOUT_PROCESSED: "RIDER_PAYOUT_PROCESSED",
  ADMIN_EARNING_CREDITED: "ADMIN_EARNING_CREDITED",
  COD_REMITTED: "COD_REMITTED",
  REFUND: "REFUND",
  ADJUSTMENT: "ADJUSTMENT",
  WITHDRAWAL: "WITHDRAWAL",
  CANCELLATION_REVERSAL: "CANCELLATION_REVERSAL",
  WALLET_REFUND: "WALLET_REFUND",
};

export const PAYOUT_TYPE = {
  SELLER: "SELLER",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
};

export const PAYOUT_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const COMMISSION_TYPE = {
  PERCENTAGE: "percentage",
  FIXED: "fixed",
};

export const COMMISSION_FIXED_RULE = {
  PER_ITEM: "per_item",
  PER_QTY: "per_qty",
};

export const HANDLING_FEE_TYPE = {
  NONE: "none",
  FIXED: "fixed",
  PERCENTAGE: "percentage",
};

export const HANDLING_FEE_STRATEGY = {
  HIGHEST_CATEGORY_FEE: "highest_category_fee",
  SUM_OF_CATEGORY_FEES: "sum_of_category_fees",
  MAX_SINGLE_FEE: "max_single_fee",
  PER_ITEM_FEE: "per_item_fee",
};

export const DELIVERY_PRICING_MODE = {
  FIXED_PRICE: "fixed_price",
  DISTANCE_BASED: "distance_based",
};

export const FINANCE_AUDIT_ACTION = {
  ORDER_FINANCE_SNAPSHOT_FROZEN: "ORDER_FINANCE_SNAPSHOT_FROZEN",
  ONLINE_PAYMENT_VERIFIED: "ONLINE_PAYMENT_VERIFIED",
  COD_MARKED_COLLECTED: "COD_MARKED_COLLECTED",
  COD_RECONCILED: "COD_RECONCILED",
  ORDER_DELIVERED_SETTLED: "ORDER_DELIVERED_SETTLED",
  PAYOUT_QUEUED: "PAYOUT_QUEUED",
  PAYOUT_PROCESSED: "PAYOUT_PROCESSED",
  DELIVERY_SETTINGS_UPDATED: "DELIVERY_SETTINGS_UPDATED",
  FINANCE_ADJUSTMENT_APPLIED: "FINANCE_ADJUSTMENT_APPLIED",
};

export const ALL_PAYMENT_MODES = Object.values(PAYMENT_MODE);
export const ALL_ORDER_PAYMENT_STATUSES = Object.values(ORDER_PAYMENT_STATUS);
export const ALL_ORDER_SETTLEMENT_STATUSES = Object.values(ORDER_SETTLEMENT_STATUS);
export const ALL_OWNER_TYPES = Object.values(OWNER_TYPE);
export const ALL_WALLET_STATUSES = Object.values(WALLET_STATUS);
export const ALL_LEDGER_DIRECTIONS = Object.values(LEDGER_DIRECTION);
export const ALL_LEDGER_STATUSES = Object.values(LEDGER_STATUS);
export const ALL_LEDGER_TRANSACTION_TYPES = Object.values(LEDGER_TRANSACTION_TYPE);
export const ALL_PAYOUT_TYPES = Object.values(PAYOUT_TYPE);
export const ALL_PAYOUT_STATUSES = Object.values(PAYOUT_STATUS);
export const ALL_COMMISSION_TYPES = Object.values(COMMISSION_TYPE);
export const ALL_COMMISSION_FIXED_RULES = Object.values(COMMISSION_FIXED_RULE);
export const ALL_HANDLING_FEE_TYPES = Object.values(HANDLING_FEE_TYPE);
export const ALL_HANDLING_FEE_STRATEGIES = Object.values(HANDLING_FEE_STRATEGY);
export const ALL_DELIVERY_PRICING_MODES = Object.values(DELIVERY_PRICING_MODE);
export const ALL_FINANCE_AUDIT_ACTIONS = Object.values(FINANCE_AUDIT_ACTION);
