export const QC_ROUTES = {
  HOME: "/qc",
  CATEGORIES: "/qc/categories",
  CATEGORY: (id) => `/qc/category/${id}`,
  PRODUCT: (id) => `/qc/product/${id}`,
  SEARCH: "/qc/search",
  STORE: (slug) => `/qc/store/${slug}`,
  CART: "/qc/cart",
  CHECKOUT: "/qc/checkout",
  ORDERS: "/qc/orders",
  ORDER_DETAIL: (id) => `/qc/orders/${id}`,
  TRANSACTIONS: "/qc/transactions",
  PROFILE: "/qc/profile",
  PROFILE_EDIT: "/qc/profile/edit",
  WISHLIST: "/qc/wishlist",
  ADDRESSES: "/qc/addresses",
  WALLET: "/qc/wallet",
  SUPPORT: "/qc/support",
  CHAT: "/qc/chat",
  PAYMENT_STATUS: "/qc/payment-status",
  PRIVACY: "/qc/privacy",
  TERMS: "/qc/terms",
  ABOUT: "/qc/about",

  // Admin Routes
  ADMIN_DASHBOARD: "/qc/admin/dashboard",
  ADMIN_PRODUCTS: "/qc/admin/products",
  ADMIN_CATEGORIES: "/qc/admin/categories",
  ADMIN_ORDERS: "/qc/admin/orders",
  ADMIN_STORES: "/qc/admin/stores",
  ADMIN_BANNERS: "/qc/admin/banners",
  ADMIN_COUPONS: "/qc/admin/coupons",
  ADMIN_SETTINGS: "/qc/admin/settings",
};
